# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.9.1
_src_path: gh:rostools/template-workshop
for_rostools: true
github_repo: r-cubed-intermediate
github_user: rostools
workshop_type: r
