flavor = "quarto"
line-width = 72
exclude = [
  ".git/",
  ".github/",
  "LICENSE.md",
  "slides/*.qmd",
  "README.md"
]

[format]
tab-width = 2

[extensions]
# This stops formatting of `@` eg `@sec-`
example-lists = false

[linters]
r = "jarl"
