# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_commit_msg: "chore(pre-commit): :pencil2: automatic fixes"
  autoupdate_commit_msg: "ci(pre-commit): :construction_worker: update pre-commit CI version"

repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Use the mirror since the main `typos` repo has tags for different
  # sub-packages, which confuses pre-commit when it tries to find the latest
  # version
  - repo: https://github.com/adhtruong/mirrors-typos
    rev: v1.45.1
    hooks:
      - id: typos

  - repo: https://github.com/posit-dev/air-pre-commit
    # Air version
    rev: 0.9.0
    hooks:
      # Run the formatter
      - id: air-format

  - repo: https://github.com/jolars/panache
    rev: panache-formatter-v0.2.1
    hooks:
      - id: panache-format

  - repo: https://github.com/rvben/rumdl-pre-commit
    rev: v0.1.82
    hooks:
      - id: rumdl-fmt # Auto-format
