# Code of Conduct {#conduct}

Science thrives on diversity of thought and origin and we value the participation
of every member of the scientific community and want all participants to have an
enjoyable and fulfilling experience. Accordingly, all participants are expected
to show respect and courtesy to other members throughout the course, in group
work, and any activity associated with this course.

To make clear what is expected, everyone taking part in this course, including
instructors, helpers, organizers, and participants, is required to conform to
the following Code of Conduct. Organizers will enforce this code throughout
events, but you may also contact us privately; all communication will be treated
as confidential.

We are dedicated to providing a welcoming and supportive environment
for all people, regardless of background or identity. As such, we do not
tolerate behaviour that is disrespectful to our teachers or learners or that
excludes, intimidates, or causes discomfort to others. We do not tolerate
discrimination or harassment based on characteristics that include, but are not
limited to, gender identity and expression, sexual orientation, disability,
physical appearance, body size, citizenship, nationality, ethnic or social
origin, pregnancy, familial status, veteran status, genetic information,
religion or belief (or lack thereof), membership of a national minority,
property, age, education, socio-economic status, technical choices, and
experience level.

Everyone who participates in this course's activities is required to conform to
this Code of Conduct. It applies to all spaces associated with this course
including, but not limited to, group work, emails, and any online forums such as
GitHub and Twitter. By participating, participants indicate their acceptance of
the procedures by which the instructors and organizers resolves any Code of
Conduct incidents.

## Expected Behavior

All course participants are expected to show respect and courtesy to others. All
interactions should be professional regardless of platform: either online or
in-person. In order to foster a positive and professional learning environment
we encourage the following kinds of behaviours in all interactions during this
course:

- Be kind and aware of your words
- Use welcoming and inclusive language
- Be respectful of different viewpoints and experiences
- Gracefully accept constructive criticism
- Focus on what is best for the course members and the community overall
- Show courtesy and respect towards other course members

See the [four social rules](https://www.recurse.com/manual#sub-sec-social-rules)
for further recommendations and details on proper behaviour.

## Unacceptable Behavior

Examples of unacceptable behavior by participants include:

- written or verbal comments which have the effect of excluding people on the basis of membership of any specific group
- causing someone to fear for their safety, such as through stalking, following, or intimidation
- violent threats or language directed against another person
- the display of sexual or violent images
- unwelcome sexual attention
- non-consensual or unwelcome physical contact
- sustained disruption of talks, events or communications
- insults or put downs
- sexist, racist, homophobic, transphobic, ableist, or exclusionary jokes
- excessive swearing
- incitement to violence, suicide, or self-harm
- continuing to initiate interaction (including photography or recording) with someone after being asked to stop
- publication of private communication without consent

## Consequences of Unacceptable Behavior

Participants who are asked, either in person or online, to stop any
inappropriate behavior are expected to comply immediately. If a participant
engages in behaviour that violates this code of conduct, the organizers,
instructors, or helpers may take any action they deem appropriate, including
warning the offender or expulsion from the course.

Thank you for helping make this a welcoming, friendly event for all `r emo::ji("smile")`

*Acknowledgements*: Large portions of this Code of Conduct were taken and modified
from other Codes of Conduct, specifically
[Software Carpentry](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html)
and [UofTCoders](https://github.com/UofTCoders/studyGroup/blob/gh-pages/codeOfConduct.md).
