# Course syllabus {#syllabus}

Reproducibility and open scientific practices are increasingly demanded of,
and needed by, scientists and researchers in our modern research environments.
We increasingly produce larger and more complex amounts of data
that often need to be heavily cleaned, reorganized, 
and processed before it can be analyzed.
This data processing often consumes the majority of the time spent coding
and doing data analysis.
And even though this stage of data analysis is so time-consuming,
there is little to no training and support provided for it.
This has led to minimal attention, scrutiny, and rigour in describing,
detailing, and reviewing these procedures in studies,
and contributes to the systemic lack of code sharing among researchers.
All together, this aspect of research is often completely hidden
and is likely to be the source of many irreproducible results.

With this course, we aim to begin addressing this gap.
Using a highly practical approach that revolves around code-along sessions
(instructor and learner coding together), hands-on exercises, and group work,
participants of the course will be able to:

1. Learn and demonstrate what an open and reproducible data analysis
workflow looks like.
1. Learn and apply the fundamental tools and skills for conducting a
reproducible and modern analysis for a research project.
1. Apply programming techniques to process and manage data in a reproducible
and well-documented way.
1. Learn where to go to get help and to continue learning modern data analysis
skills.

The course will enable participants to answer questions such as:

- What does a modern data analysis setup and workflow look like?
- How can I ensure that my data analysis project is reproducible?
- How can I create pipelines that get, process, and clean my data quickly
and that works regardless of whether there is one data file or hundreds of data files 
(i.e. it scales well)?
- How can I write code that is more reproducible, readable,
and that can be easily re-used for my future self 
and for my collaborators and colleagues?

By the end of the course, participants will: have improved their competency in
processing and wrangling datasets; have improved their proficiency in using the [R]
statistical computing language; know how to write re-usable and well-documented
code; and know how to make modern and reproducible data analysis projects. 

[R]: https://www.r-project.org/

## Is this course for you?

This course is designed a specific way and is ideal for you if:

- You are a researcher, preferably working in the biomedical field 
(ranging from experimental to epidemiological).
Specifically, this course targets those working in diabetes and metabolism.
- You currently or will soon do some quantitative data analysis.
- You either: 
    - have taken the [introduction to R course] offered in June by the DDA,
    since this course is a natural extension to that one;
    - know a *little* to a *moderate* amount of R (or computing in general); 
    - know how to use R and have *some* familiarity with the [tidyverse] and [RStudio].

[tidyverse]: https://www.tidyverse.org/
[RStudio]: https://rstudio.com/
[introduction to R course]: https://r-cubed.rostools.org/

Considering that this is a natural extension of the [introduction to R course],
I will be incorporating tools learned in that course, 
including basic Git usage as well as use of RStudio R projects.
If you *do not* have familiarity with these tools,
you will need to go over the material from the introduction course beforehand
(more details about pre-course tasks will be sent out a couple of weeks before the course).

While I have these assumptions to help focus the content of the course, if you
have an interest in learning R but don't fit any of the above assumptions, *you
are still welcome to attend the course*! 
We welcome everyone, that is until the course capacity is reached.

During the course, we **will**:

- learn how to use R, specifically those in the mid-beginner 
to early-intermediate level
- focus only on the data processing and cleaning stage of a data
analysis project
- teach from a reproducible research and open scientific
perspective (e.g. by making use of Git)
- be using practical, applied, and hands-on lessons and exercises

And we **will not** learn:

- the basics of using R and RStudio
- statistics (these are already covered by most university curriculum)

## Schedule

The workshop is structured as a series of participatory live-coding sessions
(instructor and learner coding together) interspersed with hands-on exercises
and group work, using either a practice dataset or some other real-world dataset.
There are some lectures given, mainly at the start and end of the workshop.
The general schedule outline is shown in the below table.

```{r schedule-table, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE}
options(knitr.kable.NA = "")
schedule <- readr::read_csv(
    here::here("resources/schedule.csv"),
    col_types = cols(`Date and time` = col_character(),
                     `Session topic` = col_character())
)
knitr::kable(schedule, align = "l", caption = "Overall course schedule for the 2 days.")
```

## Location

The course will be taking place at Aarhus University in two different buildings:

- **Day 1, Sept. 8th**: Building 1264, room 209

    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2221.4776486410537!2d10.202873315946679!3d56.16613558066591!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x464c3fbf0e58f8e3%3A0xb3a37fdd519e9028!2sBartholins%20All%C3%A9%201%2C%20Building%201264%2C%208000%20Aarhus!5e0!3m2!1sen!2sdk!4v1597080458787!5m2!1sen!2sdk" width="400" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>

- **Day 2, Sept. 9th**: Building 1231, room 228

    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1320.887119945961!2d10.202654769824292!3d56.16646682802605!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x464c3fbf68ccd12f%3A0x77cf8cc6f98baa58!2sWilhelm%20Meyers%20All%C3%A9%203%2C%20Building%201231%2C%208000%20Aarhus!5e0!3m2!1sen!2sdk!4v1597080711037!5m2!1sen!2sdk" width="400" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
