project:
  type: rostools-theme
  pre-render:
    - mkdir -p _temp
    - quarto render slides/*.qmd
  resources:
    - slides/*.html

book:
  title: "Intermediate Reproducible Research in R"
  subtitle: "An intermediate workshop on modern approaches and workflows to processing data"
  author:
    - name: "Luke W. Johnston"
      orcid: "0000-0003-4169-2616"
    - name: "Anders Askeland"
      orcid: "0000-0002-2996-129X"
  date: last-modified
  repo-url: "https://github.com/rostools/r-cubed-intermediate"
  site-url: "https://r-cubed-intermediate.rostools.org"
  chapters:
    - index.qmd
    - part: "Overview"
      chapters:
        - overview/syllabus.qmd
        - overview/is-this-for-you.qmd
        - overview/schedule.qmd
        - overview/learning-design.qmd
    - part: "Pre-workshop"
      chapters:
        - pre-workshop/overview.qmd
        - pre-workshop/code-of-conduct.qmd
        - pre-workshop/installing-programs-r.qmd
        - pre-workshop/installing-r-packages.qmd
        - pre-workshop/git.qmd
        - pre-workshop/create-project.qmd
        - pre-workshop/github.qmd
        - pre-workshop/download-data.qmd
        - pre-workshop/survey.qmd
    - part: "Sessions"
      chapters:
      - sessions/introduction.qmd
      - sessions/importing.qmd
      - sessions/functions.qmd
      - sessions/robustness.qmd
      - sessions/functionals.qmd
      - sessions/regex.qmd
      - sessions/split-apply-combine.qmd
      - sessions/pivots.qmd
      - sessions/joins.qmd
      - sessions/project-work.qmd
      - sessions/what-next.qmd
  appendices:
    - appendix/extras.qmd
    - appendix/for-teachers.qmd
    - appendix/references.qmd
    - CHANGELOG.md
    - CONTRIBUTING.md
    - LICENSE.md
  page-footer:
    center:
      - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
        href: LICENSE.md
      - text: "Code of Conduct"
        href: "pre-workshop/code-of-conduct.qmd"

format:
  rostools-theme-html:
    doi: "10.5281/zenodo.4061900"
    include-before-body:
      - "includes/site-counter.html"

bibliography:
  - includes/packages.bib
  - includes/references.bib

metadata-files:
  - _metadata.yml
