---
search: false
format: r3-theme-revealjs
bibliography: "../includes/references.bib"
csl: "../includes/vancouver.csl"
---

# Welcome to the Intermediate R^3^ workshop!

::::: columns
::: {.column width="70%"}
-   :heavy_check_mark: Pick a group from the basket and go to that table
-   :heavy_check_mark: Introduce yourself
-   :heavy_check_mark: Open your `LearnR3.Rproj` RStudio project
-   :heavy_check_mark: Check that your `data-raw/` looks like that on
    the right
:::

::: {.column width="30%"}
```{r, echo=FALSE, eval=FALSE}
withr::with_dir("../", {
  fs::dir_tree("data-raw/", recurse = 1)
})
```

``` text
data-raw/
├── README.md
├── mmash
│   ├── user_1
│   ├── user_10
│   ├── user_11
│   ├── ...
│   ├── user_7
│   ├── user_8
│   └── user_9
├── mmash-data.zip
└── mmash.R
```
:::
:::::

::: notes
Introduce instructors and helpers.
:::

# Motivation for this workshop {.center}

## How do you *exactly* do data analysis? What's the workflow? :thinking: {.center}

::: notes
When I started out doing research during my Masters, I always wondered
*how* do researchers go about doing data analysis... what was their
workflow *exactly* like. No one ever really taught that. Even on online
tutorials, mostly pieces of code or how to use code are taught... but
never teaching the bigger picture... How do researchers in their daily
work write R code and do their data analysis?

This question is the reason why the overall workflow is the primary
focus in this workshop and partly with the beginner one. I try to focus on
the bigger picture and the overall workflow you would do for doing data
analysis.

So, why is it that there isn't much information on how researchers do
data analysis?
:::

# :shrug::confused:...Because code sharing is almost non-existent in science {.center}

Very few papers provide code [@Leek2017a, @Considine2017a]

::: notes
It's because code sharing basically doesn't exist in the vast majority
of scientific fields. You've probably read a methods section in a paper
and wondered how exactly they did it.
:::

## Code sharing: From scientific principle of "reproducibility" {.center}

...often confused with "replicability" [@Plesser2018a] (see also
American Statistical Association
[statement](https://www.amstat.org/asa/files/pdfs/POL-ReproducibleResearchRecommendations.pdf))

. . .

::::: columns
::: {.column width="50%"}
### Replicability

-   Repeating a study by *independently* performing another identical
    study
-   Linked to the "irreproducibility crisis" (aka "irreplicability
    crisis")
:::

::: {.column width="50%"}
### Reproducibility

-   Generating the exact same results when using the same data and code
-   *Question*: If we can't even *reproduce* a study's results, how can
    we expect to replicate it?
:::
:::::

## These issues can be fixed by creating and nurturing a culture of openness {.center}

## Goal of this workshop? Start changing the culture by providing the training {.center}

# Workshop details

## Setup and layout {.smaller}

::::: columns
::: {.column width="50%"}
-   Workshop is mix of:
    -   "Code-alongs" (we type and explain, you type along)
    -   Hands-on coding, discussing, and reading exercises
    -   Dedicated practice time (potentially on your own data)
-   All material is online (and [openly
    licensed](https://r-cubed-intro.rostools.org/LICENSE.html))
-   [Resources Appendix](https://guides.rostools.org/learning.html)
    -   Material for further learning
:::

::: {.column width="50%"}
-   Reading tasks are "callout" blocks marked by the blue line on the
    left side of the text
-   Schedule listed is a *guide* only, some sessions are longer, others
    shorter
-   Less about coding, more about connecting with others
    -   During lunch, try to sit beside someone you don't know
    -   Several networking activities (usually after lunch)
-   Feedback collected at end of every day, it is so helpful and
    important for improving the workshop :grin:
:::
:::::

::: notes
Explain a bit more about the reading, why doing it, and that this workshop
in particular has a lot more of it than more advanced workshops.

About feedback, will improve this workshop, we're collaborating together
to make it better. You're learning, but also helping to improve the
material and in how we teach you. What makes sense, what is confusing,
and so on.
:::

## Getting or asking for help :raising_hand_woman::raising_hand_man: {.center}

::::: columns
::: column
-   Put the origami hat on your laptop to get help
    -   There are lots of helpers
    -   Table mates, you can help out too
:::

::: column
-   We're all learning here!
    -   This is a supportive and safe environment
    -   Remember our [Code of Conduct](conduct.html)
:::
:::::

## Practice using origami hats: Does your `data-raw/` look as this? {.center}

``` text
data-raw/
├── README.md
├── mmash
│   ├── user_1
│   ├── user_10
│   ├── user_11
│   ├── ...
│   ├── user_7
│   ├── user_8
│   └── user_9
├── mmash-data.zip
└── mmash.R
```

# Activities

## :walking::walking_woman: How do you perceive your skill in R? {.center}

::: notes
Along the wall, arrange to one side is "novice/basic" and other side is
"advanced".
:::

## :walking::walking_woman: Who has had formal training in specifically *coding* in R or in general? {.center}

::: notes
One side of the room is yes, the other side is no. Can also be in the
middle if you aren't completely sure. If the workshop was part of a
statistics workshop, it doesn't really count.
:::

## :walking_woman::walking: Who has struggled with using R? {.center}

::: notes
One side of the room if yes, other side if no, middle if you've sort have
struggled.
:::

## :raising_hand: Who has seen or worked with "true" data analysis pipelines (e.g. run a single command and *everything* gets re-done)? {.center}

::: notes
More for my personal interest. The word pipeline gets thrown around a
lot, but how many have encountered, made, or used true pipelines?
Automated from beginning to end.
:::

## 💬 For those that have done or are doing data processing, does it take up a lot of time? How much? {.center}

::: notes
Question, mostly for my own information...
:::

## Return to your seats! :chair: {.center}

# References
