# Workshop syllabus {#sec-syllabus}

Reproducibility and open scientific practices are increasingly demanded
of, and needed by, scientists and researchers in our modern research
environments. We increasingly produce larger and more complex amounts of
data that often need to be heavily cleaned, reorganized, and processed
before it can be analyzed. This data processing often consumes the
majority of the time spent coding and doing data analysis. And even
though this stage of data analysis is so time-consuming, there is little
to no training and support provided for it. This has led to minimal
attention, scrutiny, and rigour in describing, detailing, and reviewing
these procedures in studies, and contributes to the systemic lack of
code sharing among researchers. All together, this aspect of research is
often completely hidden and may likely to be the source of many
irreproducible results.

With this workshop, we aim to begin addressing this gap. We use a highly
practical, mixed-methods, hands-on approach to learning that revolves
around code-along sessions (instructor and you, the learner, coding
together), hands-on exercises, discussion activities, reading tasks, and
group project work. The learning outcome and overall aim of the workshop
is to enable you to:

1.  Demonstrate an open and reproducible workflow in R that makes use of
    the effective and powerful functional programming approach for
    working with data, and apply it to import and process some
    real-world data.

This aim is broken down into specific learning objectives that are
spread across the workshop's sessions. The workshop will enable you to:

{{< include /include/_learning-objectives-importing.qmd >}}
{{< include /include/_learning-objectives-functions.qmd >}}
{{< include /include/_learning-objectives-functionals.qmd >}}
{{< include /include/_learning-objectives-dplyr-joins.qmd >}}
{{< include /include/_learning-objectives-pivots.qmd >}}

To simplify this into tangible tools and methods, during the workshop we
will:

1.  Use a function-based workflow to writing code.
2.  Use `{usethis}`'s `use_package()` function to manage package
    dependencies.
3.  Use [Quarto](https://quarto.org) to write reproducible documents.
4.  Use [Git](https://git-scm.com) and [GitHub](https://github.com) to
    manage code and version control.
5.  Use the functional programming tools with `{purrr}`'s `map()` and
    `reduce()` functions.
6.  Use the split-apply-combine technique to summarize data with
    `{dplyr}`'s `group_by()`, `summarise()`, and `across()` functions.
7.  Use the `{dplyr}` package to `full_join()` datasets together.
8.  Use the `{tidyr}` package to pivot data from long with
    `pivot_longer()` to wide with `pivot_wider()`.

Learning and coding are not just solo activities, they are also very
much social activities. So throughout the workshop, we provide plenty of
opportunity to meet new people, share experiences, have discussion
activities, and work in groups.

## Is this workshop for you? {#sec-is-it-for-you}

This workshop is designed in a specific way and is ideal for you if:

-   You are a researcher, preferably working in the biomedical field
    (ranging from experimental to clinical to epidemiological).
-   You currently are or will soon do quantitative data analysis.
-   You either:
    -   have taken the [introduction to Reproducible Research in R
        workshop](https://r-cubed-intro.rostools.org/), as this
        intermediate workshop is a natural extension to that the
        introduction one;
    -   know a *little* to a *moderate* amount of R (or computing in
        general);
    -   know how to use R and have *some* familiarity with the
        [tidyverse](https://www.tidyverse.org/) and
        [RStudio](https://rstudio.com/).

Considering that this is a natural extension of the [introductory
r-cubed workshop](https://r-cubed-intro.rostools.org/), this workshop
incorporates tools learned during that workshop, including basic Git
usage as well as the use of RStudio R Projects. If you *do not* have
familiarity with these tools, you will need to go over the material from
the introduction workshop beforehand (more details about pre-workshop
tasks will be sent out a couple of weeks before the workshop).

We make these assumptions about you as the learner to help focus the
content of the workshop, however, if you have an interest in learning R
but don't fit any of the above assumptions, **you are still welcome to
attend the workshop**! We welcome everyone, that is until the workshop
capacity is reached.

During the workshop, we **will**:

-   Learn how to use R, specifically in the mid-beginner to
    early-intermediate level.
-   Focus only on the data processing and cleaning stage of a data
    analysis project.
-   Teach from a reproducible research and open scientific perspective
    (e.g. by making use of Git).
-   Be using practical, applied, and hands-on lessons and exercises.
-   Apply evidence-based teaching practices.
-   Use a real-world dataset to work with.

And we **will not**:

-   Go over the basics of using R and RStudio.
-   Cover any statistics, as these are already covered by most
    university curriculum.
