# Project work

:::: {.alert .alert-warning .hints-alert}
::: {.hints-container}
Note: we're still testing to see what best works for this section.)
:::
::::

For the most part, we thought the best way to reinforce and practice the
skills learned in this course is to apply them to your own datasets or projects.
So we set aside time in the schedule for this work under the heading of "project work".
However, if you don't have data to work on, you have several other options:

- Work more on the MMASH dataset, analyzing it and exploring it more.
- Practice the skills and tools learned by starting from beginning on a new
dataset. For this option, there are several data sources you could use like
[PhysioNet](https://physionet.org/about/database/#open) or 
[Zenodo](https://zenodo.org/search?page=1&size=20&q=diabetes&access_right=open&file_type=xlsx&file_type=csv&file_type=zip&type=dataset#).
Here are two possible datasets you could use that require the skills and tools 
we covered in this course:
    - [Data on the 2021 Olympics in Tokyo](https://www.kaggle.com/arjunprasadsarkhel/2021-olympics-in-tokyo)
    - [RR interval time series from healthy subjects](https://physionet.org/content/rr-interval-healthy-subjects/1.0.0/) 
- Work on the game ["Murder Mystery"](https://andersaskeland.github.io/R-murder-mystery) (which Anders converted into a game using R).
