# Is this for you? {#sec-is-this-for-you}

To help manage expectations and develop the material for this workshop,
we make a few assumptions about *who you are* as a participant in the
workshop.

We assume you can relate to one or more of the following:

-   You are a researcher, preferably working in the biomedical field
    (ranging from experimental to clinical to epidemiological).
-   You currently are or will soon do quantitative data analysis.
-   You either:
    -   have taken the [introduction to Reproducible Research in R
        workshop](https://r-cubed-intro.rostools.org/), as this
        intermediate workshop is a natural extension to that the
        introduction one;
    -   know a *little* to a *moderate* amount of R (or computing in
        general);
    -   know how to use R and have *some* familiarity with the
        [tidyverse](https://www.tidyverse.org/) and
        [RStudio](https://rstudio.com/).


Considering that this is a natural extension of the [introductory
r-cubed workshop](https://r-cubed-intro.rostools.org/), this workshop
incorporates tools learned during that workshop, including basic Git
usage as well as the use of RStudio R Projects. If you *do not* have
familiarity with these tools, you will need to go over the material from
the introduction workshop beforehand (more details about pre-workshop
tasks will be sent out a couple of weeks before the workshop).

We make these assumptions about you as the learner to help focus the
content of the workshop, however, if you have an interest in learning R
but don't fit any of the above assumptions, **you are still welcome to
attend the workshop**! We welcome everyone, that is until the workshop
capacity is reached.

In addition to the assumptions above, the workshop also has a fairly
focused scope, which may also help you decide if this workshop is for
you. During the workshop, we **will**:

-   Learn how to use R, specifically in the mid-beginner to
    early-intermediate level.
-   Focus only on the data processing and cleaning stage of a data
    analysis project.
-   Teach from a reproducible research and open scientific perspective
    (e.g. by making use of Git).
-   Be using practical, applied, and hands-on lessons and exercises.
-   Apply evidence-based teaching practices.
-   Use a real-world dataset to work with.

And we **will not**:

-   Go over the basics of using R and RStudio.
-   Cover any statistics, as these are already covered by most
    university curriculum.
