<!-- NOTE: This file was generated from the `template-workshop` template. -->

# Learning design {#sec-learning-design}

This workshop is designed using the science of learning. Learning is
when new content gets incorporated into long-term storage in the brain
in a way that it can be later retrieved. Some of the best ways to enable
learning is to do "active learning" by engaging with the material,
practicing retrieving what was just covered, repeatedly being exposed to
the content, linking the new information with what you already know, and
explaining it to someone else.

We use a variety of activities to target the different "pathways" of
learning. A big part of learning is being engaged in the *process* of
learning, not just learning the content itself. So to help you be
engaged in your own learning, we want to involve you in the reasons
*why* we do the things we do during this workshop.

Throughout the workshop, we use these practices to support learning.

## Clear learning goals and a strong narrative

The learning goals and the narrative are tightly connected in this
workshop. Learning is easier when you have a better idea of where you
are going, where you are relative to the end goal, and what to expect
along the way.

## "Code-alongs" as the main activity

"Code-alongs" is when the teacher types on their computer that is on the
projector and explains what it means as you also type along with them.
The connection between using the hands and doing something tangible
helps reinforce learning. It also helps the teachers to go slower as we
have to both explain and type things out. This helps you learn better.
"Less is more" works very well with learning.

## Retrieval practice with hands-on exercises

Hands-on exercises reinforce what was just taught through retrieval
practice and repetition. It gives you a chance to engage with the
material and the space to try it out on your own. This helps you form a
better sense of how to do it yourself.

## Linking new information with existing knowledge with discussion activities

Discussion activities encourage linking what you already know and do in
your work with the new information. Because humans are social beings, we
also tend to learn better when there is some social aspect to it. For
example, explaining something to someone else is one of the best ways to
learn, as nicely expressed in the quote "while we teach, we learn" from
the Roman philosopher Seneca.

## Minimal use of lectures

Lectures, while extremely common, are forms of information sharing with
the lowest rates of learning. In this workshop, we use reading tasks
instead, so you can go at your pace, re-read things you may not
understand, and take notes, all of which support learning. To help
reinforce what you just read, the teacher will briefly summarise and
emphasise key points after reading tasks, to repeat the main points and
target another part of the brain (the auditory pathway).

## Frequent breaks and variation in activities

Breaks are how your brain can recharge and refocus. The brain is only
able to effectively focus on one thing at a time in 30-50 minute blocks
of time. That's why we mix together code-alongs, exercises, discussions,
and reading to give your brain some variation. Having an explicit break,
even 5 minutes, is enough for the brain to better process and store what
was covered.

## Easily accessible material that is online, always

All the material is online on this website, so that it is easy for you
to go back to after the workshop. This builds the repetition and
retrieval practice part of learning. Our brains also get easily
distracted, which is completely normal. So if you get distracted during
the workshop, you can simply go to the material and get caught up with
where we are. We also make sure to follow the material on the website
closely, so that it is easier for you to follow along.

## A safe and supportive environment

Mental safety in a supportive environment is critical for effective
learning. It puts the brain into a more relaxed state that allows for
optimal processing and ultimately learning. That's why we try to
explicitly create that space, for example with the use of our Code of
Conduct.

## Using origami hats to ask for help

Asking for help can feel difficult, especially when you are learning and
are unsure about something. To make it easier and feel safer, we use
origami hats (or stickies) to show how everyone is doing. If you need
help, you put up the "help" hat (usually orange) and a helper will come
to you as soon as possible. If not, you can put up a "all good" hat
(usually blue) to let us know you are following along. Since we often
have several helpers, you usually won't wait long. This simple system
lets you ask for help without interrupting the teacher or drawing
attention, so you can keep following along while you wait. Our goal is
to make getting help easier and more comfortable.

## Being involved in the learning process

Now you know a bit more about the thoughts behind how we've designed
this workshop to really try to support and enable your own learning!
:tada: :grin:
