# Syllabus {#sec-syllabus}

```{r}
#| include: false
# To trigger linking.
library(purrr)
library(dplyr)
```

Reproducibility and open scientific practices are increasingly demanded
of, and needed by, scientists and researchers in our modern research
environments. We increasingly produce larger and more complex amounts of
data that often need to be heavily cleaned, reorganized, and processed
before it can be analysed. This data processing often consumes the
majority of the time spent coding and doing data analysis. And even
though this stage of data analysis is so time-consuming, there is little
to no training and support provided for it. This has led to minimal
attention, scrutiny, and rigour in describing, detailing, and reviewing
these procedures in studies, and contributes to the systemic lack of
code sharing among researchers. All together, this aspect of research is
often completely hidden and may likely be the source of many
irreproducible results.

In this workshop we aim to begin addressing this gap. We use a highly
practical, mixed-methods, hands-on approach to learning that revolves
around code-along sessions (teacher and you, the learner, coding
together), hands-on exercises, discussion activities, reading tasks, and
team project work. This workshop is designed for to be done over 3 full
days in person, following the [schedule](/overview/schedule.qmd) listed
in @sec-schedule.

## Learning outcome and objectives

The learning outcome and overall aim of the workshop is to enable you
to:

1. Demonstrate an open and reproducible workflow in R that makes use of
   the effective and powerful functional programming approach for
   working with data, and apply it to import and process some real-world
   data.

This aim is broken down into specific learning objectives that are
spread across the workshop's sessions. The workshop will enable you to:

[Pre-process data as you import it](/sessions/importing.qmd)

{{< include /includes/objectives/_importing.qmd >}}

[Bundle code into functions](/sessions/functions.qmd)

{{< include /includes/objectives/_functions.qmd >}}

[Making robust and reusable functions](/sessions/robustness.qmd)

{{< include /includes/objectives/_robustness.qmd >}}

[Doing many things at once with functionals](/sessions/functionals.qmd)

{{< include /includes/objectives/_functionals.qmd >}}

[Processing strings with regular expressions](/sessions/regex.qmd)

{{< include /includes/objectives/_regex.qmd >}}

[Using split-apply-combine to help in processing](/sessions/split-apply-combine.qmd)

{{< include /includes/objectives/_split-apply-combine.qmd >}}

[Pivoting your data from and to long or wide](/sessions/pivots.qmd)

{{< include /includes/objectives/_pivots.qmd >}}

[Joining data together](/sessions/joins.qmd)

{{< include /includes/objectives/_joins.qmd >}}

To simplify this into tangible tools and methods, during the workshop we
will:

1. Use a function-based workflow to writing code.
2. Use `{usethis}`'s `use_package()` function to manage package
   dependencies.
3. Use [Quarto](https://quarto.org) to write reproducible documents.
4. Use [Git](https://git-scm.com) and [GitHub](https://github.com) to
   manage code and version control.
5. Use the functional programming tools like `{purrr}`'s `map()`
   function.
6. Use the `{lubridate}` package to clean and process dates and times.
7. Use the `{stringr}` package and regular expressions to clean and
   process character strings.
8. Use the split-apply-combine technique to summarize data with
   `{dplyr}`'s `group_by()`, `summarise()`, and `across()` functions.
9. Use the `{tidyr}` package to pivot data from long with
   `pivot_longer()` to wide with `pivot_wider()`.
10. Use the `{dplyr}` package to `full_join()` datasets together.

Learning and coding are not just solo activities, they are also very
much social activities. So throughout the workshop, we provide plenty of
opportunity to meet new people, share experiences, have discussion
activities, and work in groups.
