name: Build website for R-based educational material 

on:
  push:
    branches: main

jobs:
  build-deploy-docs:
    uses: rostools/.github/.github/workflows/reusable-build-website-r.yml@main
    secrets:
      netlify-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
