name: Build website for course

on:
  push:
    branches: main

jobs:
  build-deploy-docs:
    uses: rostools/.github/.github/workflows/reusable-build-website.yml@main
    secrets:
      netlify-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
